ALTER TABLE projects
ALTER COLUMN status DROP DEFAULT;

ALTER TABLE projects
ALTER COLUMN status TYPE TEXT
USING (CASE WHEN status = true THEN 'ACTIVE' ELSE 'INACTIVE' END);

ALTER TABLE projects
ALTER COLUMN status SET DEFAULT 'ACTIVE';
