// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateShard(arg1) {
  return window['go']['main']['App']['ActivateShard'](arg1);
}

export function Activateproject(arg1) {
  return window['go']['main']['App']['Activateproject'](arg1);
}

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function AddShard(arg1) {
  return window['go']['main']['App']['AddShard'](arg1);
}

export function CommitSchemaDraft(arg1, arg2) {
  return window['go']['main']['App']['CommitSchemaDraft'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateSchemaDraft(arg1, arg2) {
  return window['go']['main']['App']['CreateSchemaDraft'](arg1, arg2);
}

export function DeactivateShard(arg1) {
  return window['go']['main']['App']['DeactivateShard'](arg1);
}

export function Deactivateproject(arg1) {
  return window['go']['main']['App']['Deactivateproject'](arg1);
}

export function DeleteAllShards(arg1) {
  return window['go']['main']['App']['DeleteAllShards'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSchemaDraft(arg1) {
  return window['go']['main']['App']['DeleteSchemaDraft'](arg1);
}

export function DeleteShard(arg1) {
  return window['go']['main']['App']['DeleteShard'](arg1);
}

export function ExecuteProjectSchema(arg1) {
  return window['go']['main']['App']['ExecuteProjectSchema'](arg1);
}

export function ExecuteSQL(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSQL'](arg1, arg2);
}

export function FetchConnectionInfo(arg1) {
  return window['go']['main']['App']['FetchConnectionInfo'](arg1);
}

export function FetchProjectByID(arg1) {
  return window['go']['main']['App']['FetchProjectByID'](arg1);
}

export function FetchProjectStatus(arg1) {
  return window['go']['main']['App']['FetchProjectStatus'](arg1);
}

export function FetchShardKeys(arg1) {
  return window['go']['main']['App']['FetchShardKeys'](arg1);
}

export function FetchShardStatus(arg1) {
  return window['go']['main']['App']['FetchShardStatus'](arg1);
}

export function GetCurrentSchema(arg1) {
  return window['go']['main']['App']['GetCurrentSchema'](arg1);
}

export function GetFailedShardExecutions(arg1) {
  return window['go']['main']['App']['GetFailedShardExecutions'](arg1);
}

export function GetProjectSchemaStatus(arg1) {
  return window['go']['main']['App']['GetProjectSchemaStatus'](arg1);
}

export function GetSchemaCapabilities(arg1) {
  return window['go']['main']['App']['GetSchemaCapabilities'](arg1);
}

export function GetSchemaExecutionStatus(arg1) {
  return window['go']['main']['App']['GetSchemaExecutionStatus'](arg1);
}

export function GetSchemaHistory(arg1) {
  return window['go']['main']['App']['GetSchemaHistory'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListShards(arg1) {
  return window['go']['main']['App']['ListShards'](arg1);
}

export function MonitorShards(arg1) {
  return window['go']['main']['App']['MonitorShards'](arg1);
}

export function RecomputeKeys(arg1) {
  return window['go']['main']['App']['RecomputeKeys'](arg1);
}

export function ReplaceShardKeys(arg1, arg2) {
  return window['go']['main']['App']['ReplaceShardKeys'](arg1, arg2);
}

export function RetrySchemaExecution(arg1) {
  return window['go']['main']['App']['RetrySchemaExecution'](arg1);
}

export function RetryShardConnections(arg1) {
  return window['go']['main']['App']['RetryShardConnections'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateProjectSchemaDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProjectSchemaDraft'](arg1, arg2, arg3);
}
