// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {executor} from '../models';
import {main} from '../models';
import {context} from '../models';

export function ActivateShard(arg1:string):Promise<void>;

export function Activateproject(arg1:string):Promise<void>;

export function AddConnection(arg1:repository.ShardConnection):Promise<void>;

export function AddShard(arg1:string):Promise<repository.Shard>;

export function CommitSchemaDraft(arg1:string,arg2:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<repository.Project>;

export function CreateSchemaDraft(arg1:string,arg2:string):Promise<repository.ProjectSchema>;

export function DeactivateShard(arg1:string):Promise<void>;

export function Deactivateproject(arg1:string):Promise<void>;

export function DeleteAllShards(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSchemaDraft(arg1:string):Promise<void>;

export function DeleteShard(arg1:string):Promise<string>;

export function ExecuteProjectSchema(arg1:string):Promise<void>;

export function ExecuteSQL(arg1:string,arg2:string):Promise<Array<executor.ExecutionResult>>;

export function FetchConnectionInfo(arg1:string):Promise<repository.ShardConnection>;

export function FetchProjectByID(arg1:string):Promise<repository.Project>;

export function FetchProjectStatus(arg1:string):Promise<string>;

export function FetchShardKeys(arg1:string):Promise<Array<repository.ShardKeys>>;

export function FetchShardStatus(arg1:string):Promise<string>;

export function GetCurrentSchema(arg1:string):Promise<repository.ProjectSchema>;

export function GetFailedShardExecutions(arg1:string):Promise<Array<repository.SchemaExecutionStatus>>;

export function GetProjectSchemaStatus(arg1:string):Promise<string>;

export function GetSchemaCapabilities(arg1:string):Promise<main.SchemaCapabilities>;

export function GetSchemaExecutionStatus(arg1:string):Promise<Array<repository.SchemaExecutionStatus>>;

export function GetSchemaHistory(arg1:string):Promise<Array<repository.ProjectSchema>>;

export function ListProjects():Promise<Array<repository.Project>>;

export function ListShards(arg1:string):Promise<Array<repository.Shard>>;

export function MonitorShards(arg1:context.Context):Promise<void>;

export function RecomputeKeys(arg1:string):Promise<void>;

export function ReplaceShardKeys(arg1:string,arg2:Array<repository.ShardKeyRecord>):Promise<void>;

export function RetrySchemaExecution(arg1:string):Promise<void>;

export function RetryShardConnections(arg1:context.Context):Promise<void>;

export function UpdateConnection(arg1:repository.ShardConnection):Promise<void>;
