// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateShard(arg1) {
  return window['go']['main']['App']['ActivateShard'](arg1);
}

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function AddShard(arg1) {
  return window['go']['main']['App']['AddShard'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeactivateShard(arg1) {
  return window['go']['main']['App']['DeactivateShard'](arg1);
}

export function DeleteAllShards(arg1) {
  return window['go']['main']['App']['DeleteAllShards'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteShard(arg1) {
  return window['go']['main']['App']['DeleteShard'](arg1);
}

export function FetchConnectionInfo(arg1) {
  return window['go']['main']['App']['FetchConnectionInfo'](arg1);
}

export function FetchProjectByID(arg1) {
  return window['go']['main']['App']['FetchProjectByID'](arg1);
}

export function FetchShardStatus(arg1) {
  return window['go']['main']['App']['FetchShardStatus'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListShards(arg1) {
  return window['go']['main']['App']['ListShards'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
